



function change(){
document.getElementById('para').innerHTML ="Commençons par une définition simple du RPG. Abréviation de Role Playing Game, il consiste à vous mettre dans la peau d'un personnage et à le faire vivre à travers une multitude d'histoiresDifférent de vous en tout point ou bien similaire sur quelques traits de caractères, c'est vous qui décidez : vous façonnez votre personnage comme bon vous semble.Son physique, sa personnalité, ses qualités, ses défauts, son histoire, sa famille, tout ça forme un ensemble d'éléments que vous êtes libres de définir.</br>";
document.getElementById('para2').innerHTML ="Commençons par une définition simple du RPG. Abréviation de Role Playing Game, il consiste à vous mettre dans la peau d'un personnage et à le faire vivre à travers une multitude d'histoiresDifférent de vous en tout point ou bien similaire sur quelques traits de caractères, c'est vous qui décidez : vous façonnez votre personnage comme bon vous semble.Son physique, sa personnalité, ses qualités, ses défauts, son histoire, sa famille, tout ça forme un ensemble d'éléments que vous êtes libres de définir.</br><img src=\"img/image2.png\" width=\"500\" height=\"250\" />" ;
document.getElementById('para3').innerHTML ="Commençons par une définition simple du RPG. Abréviation de Role Playing Game, il consiste à vous mettre dans la peau d'un personnage et à le faire vivre à travers une multitude d'histoiresDifférent de vous en tout point ou bien similaire sur quelques traits de caractères, c'est vous qui décidez : vous façonnez votre personnage comme bon vous semble.Son physique, sa personnalité, ses qualités, ses défauts, son histoire, sa famille, tout ça forme un ensemble d'éléments que vous êtes libres de définir.</br><img src=\"img/darksouls-2.jpg\" width=\"500\" height=\"250\" />" ;
document.getElementById('para4').innerHTML ="Commençons par une définition simple du RPG. Abréviation de Role Playing Game, il consiste à vous mettre dans la peau d'un personnage et à le faire vivre à travers une multitude d'histoiresDifférent de vous en tout point ou bien similaire sur quelques traits de caractères, c'est vous qui décidez : vous façonnez votre personnage comme bon vous semble.Son physique, sa personnalité, ses qualités, ses défauts, son histoire, sa famille, tout ça forme un ensemble d'éléments que vous êtes libres de définir.</br><img src=\"img/bolgan.jpg\" width=\"500\" height=\"250\" />" ;
document.getElementById('para5').innerHTML ="Commençons par une définition simple du RPG. Abréviation de Role Playing Game, il consiste à vous mettre dans la peau d'un personnage et à le faire vivre à travers une multitude d'histoiresDifférent de vous en tout point ou bien similaire sur quelques traits de caractères, c'est vous qui décidez : vous façonnez votre personnage comme bon vous semble.Son physique, sa personnalité, ses qualités, ses défauts, son histoire, sa famille, tout ça forme un ensemble d'éléments que vous êtes libres de définir.</br><img src=\"img/dragon.jpg\" width=\"500\" height=\"250\" />" ;
 }
